import enum
from sqlalchemy import Enum


class SessionType(enum.Enum):
    PLAN = "PLAN"
    SERIES = "SERIES"
    RECITATION = "RECITATION"
    RECITATION_COLLECTION = "RECITATION_COLLECTION"
    GROUP_RECITATION_COLLECTION = "GROUP_RECITATION_COLLECTION"
    TIMER = "TIMER"
    ACCUMULATOR = "ACCUMULATOR"
    GROUP_ACCUMULATOR = "GROUP_ACCUMULATOR"


COLLECTION_SESSION_TYPES = (
    SessionType.RECITATION_COLLECTION,
    SessionType.GROUP_RECITATION_COLLECTION,
)

SessionTypeEnum = Enum(SessionType)