# Error codes
BAD_REQUEST = "Bad request"
NOT_FOUND = "Not found"
FORBIDDEN = "Forbidden"
CONFLICT = "Conflict"

# Accumulator messages
ACCUMULATOR_NOT_FOUND = "Accumulator not found"
ACCUMULATOR_ALREADY_EXISTS = "An accumulator already exists for this preset"
MALA_IMAGE_NOT_FOUND = "Mala image not found"
PRESET_NOT_FOUND = "Preset accumulator not found"
MANTRA_NOT_FOUND = "Mantra not found"
ACCUMULATOR_UPDATE_NOT_ALLOWED = "You don't have permission to update this accumulator"
ACCUMULATOR_DELETE_NOT_ALLOWED = "You don't have permission to delete this accumulator"
ONLY_USER_ACCUMULATORS_CAN_BE_UPDATED = "Only user-created accumulators can be updated"
ONLY_USER_ACCUMULATORS_CAN_BE_DELETED = "Only user-created accumulators can be deleted"
ONLY_PRESET_ACCUMULATORS_CAN_BE_UPDATED = "Only preset accumulators can be updated"
ONLY_PRESET_ACCUMULATORS_CAN_BE_DELETED = "Only preset accumulators can be deleted"
INVALID_COUNT = "Count must be a positive integer"
INVALID_URL = "Link URL must be a valid http or https URL"
PRESET_METADATA_REQUIRED = "At least one metadata entry with a name is required"
