

AUTHOR_NOT_FOUND = "Author not found"
AUTHOR_UPDATE_INVALID = "Invalid update request"
AUTHOR_NOT_VERIFIED = "Author not verified"
AUTHOR_NOT_ACTIVE = "Author not active"
REGISTRATION_MESSAGE = "Registration successful. Please check your email to verify your account."

EMAIL_ALREADY_VERIFIED = "Email already verified"
EMAIL_VERIFIED_SUCCESS = "Email verified successfully. Your account is pending admin approval"

PASSWORD_EMPTY = "Password cannot be empty"
PASSWORD_LENGTH_INVALID = "Password must be between 8 and 20 characters"
INVALID_EMAIL_PASSWORD = "Invalid email or password"

TOKEN_EXPIRED = "Verification token expired"
TOKEN_INVALID = "Invalid verification token"

EMAIL_VERIFICATION_PENDING_STATUS = "EMAIL VERIFICATION PENDING"

IMAGE_UPLOAD_SUCCESS = "Image uploaded successfully"
AUDIO_UPLOAD_SUCCESS = "Day audio uploaded successfully"
SUBTASK_AUDIO_UPLOAD_SUCCESS = "Sub task audio uploaded successfully"
AUDIO_ASSIGN_SUCCESS = "Day audio assigned successfully"
AUDIO_KEY_NOT_FOUND = "Audio not found or you do not have access to this audio key"
INVALID_AUDIO_FILE_FORMAT = "Invalid audio format. Allowed: MP3, M4A, WAV, AAC, OGG"
AUDIO_FILE_TOO_LARGE = "Audio file size exceeds limit"
UNEXPECTED_ERROR_UPLOAD = "An unexpected error occurred during upload"
INVALID_FILE_FORMAT = "Invalid file format. Only JPEG, PNG, and WebP images are allowed. Maximum size: 5MB"
FILE_TOO_LARGE = "File size exceeds 1MB limit"
AUTHOR_ALREADY_EXISTS = "Author already exists"
BAD_REQUEST = "Bad request"
TITLE_OR_AUTHOR_QUERY_REQUIRED = "title or author query is required"
EXTERNAL_PECHA_API_URL_NOT_CONFIGURED = "External Pecha API URL is not configured"
FORBIDDEN = "Forbidden"
NOT_FOUND = "Not found"
PLAN_DAY_NOT_FOUND = "Plan day not found"
TASK_SAME_DAY_NOT_ALLOWED = "Task is already in the same day"
PLAN_NOT_FOUND = "Plan not found"
PLAN_MUST_HAVE_AT_LEAST_ONE_DAY_WITH_CONTENT_TO_BE_PUBLISHED = "Plan must have at least one day with content to be published"
PLAN_START_DATE_UPDATE_NOT_ALLOWED_FOR_PUBLISHED_WITH_SUBSCRIBERS = "Cannot update start_date for a published plan with active subscribers"
PLAN_DAYS_OVERLAP_NEXT_PLAN = "Cannot add day(s): plan would extend past the start date of the next plan in the series ({next_start_date}). Only {available_days} more day(s) can be added."
PLAN_SCHEDULE_OVERLAPS_NEXT_PLAN = "This schedule would overlap the next plan in the series: the plan would end on {plan_end_date} but the next plan starts on {next_start_date}."
PLAN_SCHEDULE_OVERLAPS_PREVIOUS_PLAN = "This schedule would overlap the previous plan in the series, which ends on {previous_end_date}."
PLAN_CASCADE_SHIFT_BLOCKED = "Cannot shift '{blocking_plan_title}' forward: it is published and already has active subscribers. Update that plan's schedule manually first."
PLAN_AUTHOR_MISMATCH = "You are not authorized to update this plan"
EMAIL_IS_SENT = "Email is sent. Please check your email to verify your account."
UNAUTHORIZED_PLAN_DELETE = "You are not authorized to delete this plan"
TASK_NOT_FOUND = "Task not found"
TASK_TITLE_UPDATE_SUCCESS = "Task title updated successfully"
TASK_ORDER_UPDATE_FAIL = "Failed to update task order"
UNAUTHORIZED_TASK_DELETE = "You are not authorized to delete this task"
UNAUTHORIZED_TASK_ACCESS = "You are not authorized to access this task"
DUPLICATE_DAY_NUMBERS = "Duplicate day numbers"
SUBTASK_ORDER_FAILED = "Subtask order update failed"
DUPLICATE_TASK_ORDER = "Duplicate task order"
DUPLICATE_DISPLAY_ORDER = "Display order must be unique among items in this collection"
ALREADY_ENROLLED_IN_PLAN = "Already enrolled in this plan"
ALREADY_COMPLETED_SUB_TASK = "Already completed this sub task"
SUB_TASK_NOT_FOUND = "Sub task not found"
SUB_TASKS_NOT_COMPLETED = "Sub tasks not completed"
NO_FEATURED_PLANS_WITH_DAYS_FOUND = "No featured plans with days found"
NO_FEATURED_SERIES_FOUND = "No featured series found"
NO_SEGMENTATION_IDS_RETURNED = "No segmentation IDs returned from external API"
PECHA_SEGMENT_NOT_FOUND = "Pecha segment not found"
ERROR_GENERATING_URL = "Error generating URL"
NOTIFICATION_CREATED = "Notification created successfully"
NOTIFICATION_UPDATED = "Notification updated successfully"
NOTIFICATION_NOT_FOUND = "Notification not found for this day"
NOTIFICATION_ALREADY_EXISTS = "Notification already exists for this day"
DAY_VIDEO_NOT_FOUND = "Video not found for this day"
PLAN_VIDEO_NOT_FOUND = "Video not found for this plan"
INVALID_YOUTUBE_URL = "Invalid YouTube URL"
SUBTASK_NOT_IN_TASK = "One or more subtasks do not belong to this task"
